apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: peterelmwood-com
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/cloudsql-instances: ${{ vars.GCP_PROJECT_ID }}:${{ vars.GCP_REGION }}:${{ vars.GCP_SQL_INSTANCE }}
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      serviceAccountName: ${{ vars.GCP_RUN_SERVICE_ACCOUNT_EMAIL }}
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: peterelmwood-com
        image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REPO }}/peterelmwood-com:${{ vars.GCP_IMAGE_TAG }}
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.production
        - name: DEBUG
          value: 'False'
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: latest
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: ALLOWED_HOSTS
          value: 'peterelmwood.com,www.peterelmwood.com'
        - name: GS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: gcs-bucket-name
              key: latest
        - name: SECURE_SSL_REDIRECT
          value: 'True'
        resources:
          limits:
            cpu: '1000m'
            memory: 512Mi
          requests:
            cpu: '1000m'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
